# Project: CloseGL
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = CloseGL_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib" -L"C:/D/downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/D/downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = CloseGL.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

CloseGL_private.res: CloseGL_private.rc 
	$(WINDRES) -i CloseGL_private.rc --input-format=rc -o CloseGL_private.res -O coff 

